### ISSUE TITLE
bitcoin-core-dev mailing list is not used for discussion

### ISSUE THREAD

**Issue by laanwj** [chaincodelabs/onboarding-to-bitcoin-core#30]
The guide mentions that

> they should be determining the mergability of changes based primarily on the reviews and discussions of other Contributors on the GitHub PR, or less commonly, **the [#bitcoin-core-dev](https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-core-dev) mailing list.**

The bitcoin-core-dev list has been a notification-only list for a while. Only moderators can post. This is also reflected in the blurb. it was never used for discussion while it could be, so at some point we decided to change the purpose.

There's some discussion on the **bitcoin-dev** (no -core) list but this usually applies to topics that generally affect bitcoin, not bitcoin-core specific project issues. There's only github and the #bitcoin-core-dev IRC channel for that. Do you maybe mean that?

**Comment by willcl-ark** [comment]
Hey @laanwj thanks for reviewing that section.

You are correct that I meant the #bitcoin-dev mailing list rather than #bitcoin-core-dev.

Even though I have in my mind some contrived examples about opposition to a (Core) PR happening only on the mailing list (e.g. some opposition to say, CTV 👀), I think it's probably true that even in that case the message would be echoed on the PR if it was deemed to be relevant-enough to potentially block a merge.

Therefore it's probably simpler to just remove the part about any PR review/discussion happening on the mailing list as it's so uncommon, and not something we'd want to encourage.

I did also notice this recent [commit](https://github.com/bitcoin/bitcoin/commit/fa32ced49cf651b48e0a9cc165e45a27505a461f) but I think I need to change anything based on it.
